### ISSUE TITLE
Revoir les utilisations de random

### ISSUE THREAD

**Issue by l3miage-mieln** [JugurtaO/dilemme-g2_1#50]
Actuellement pour le random on a décidé arbitrairement des chances directement dans le code. 
Cela serait bien de donner un pourcentage de sens que l'aléatoire arrive en paramètre. 
Et je me demande pk on fait Random.nextInt()+1 .

**Comment by JugurtaO** [comment]
1. Oui ça serait bine de contrôller l'aléatoire par un  pourcentage % mais vu que ce n'est pas demandé, j'ai préféré faire du pre aléatoire. Le nextInt c'ets juste la méthode de la classe Random qui permet de générer un nombre entre 1 et le nombre passé en param exclus d'ou le +1 pour l'inclure .
